export const START_SIGNUP = 'START_SIGNUP';
export const END_SIGNUP = 'START_SIGNUP';
export const SET_SIGNUP_ERRORS = 'SET_SIGNUP_ERRORS';
export const START_LOGIN = 'START_LOGIN';
export const END_LOGIN = 'START_LOGIN';
export const SET_LOGIN_ERRORS = 'SET_LOGIN_ERRORS';