export const START_SIGNUP = 'START_SIGNUP';
export const END_SIGNUP = 'START_SIGNUP';
export const SET_SIGNUP_ERRORS = 'SET_SIGNUP_ERRORS';
export const START_LOGIN = 'START_LOGIN';
export const END_LOGIN = 'START_LOGIN';
export const SET_LOGIN_ERRORS = 'SET_LOGIN_ERRORS';
export const START_CREATE_PROJECT = 'START_CREATE_PROJECT';
export const END_CREATE_PROJECT = 'END_CREATE_PROJECT';
export const SET_PROJECT_ERRORS = 'SET_PROJECT_ERRORS';
export const CLEAR_STORE = 'CLEAR_STORE';
export const GET_PROJECT_START = 'GET_PROJECT_START';
export const GET_PROJECT_END = 'GET_PROJECT_END';
export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_END = 'FETCH_PROJECTS_END';

